### ISSUE TITLE
Integrate with another backend?

### ISSUE THREAD

**Issue by rbotafogo** [perNyfelt/ride#3]
Hello,

Would it be possible to use Ride with another backend?  In particular, curious about the effort of using Ride with fastR. I imagine it should not be too hard to do.  What do you think?

Thanks

**Comment by perNyfelt** [comment]
It should not be hard to do but a lot of work. Ride was made from the start to provide an alternative development environment compared to developing in R Studio and then try to make it work in Renjin so it's sole focus has always been on enhancing the deve experience for Renjin users. Classloading, package and project wizard, R execution, database interaction etc. all use Renjin. I think the easiest approach would be to fork Ride and make a FastRide where you replace the calls to Renjin with FastR and then rework the classloading stuff to suite the Graal approach.
